#!/usr/bin/env fish
set DIR (readlink -f (dirname (status -f)))

set distribution (cat /etc/*-release | \
   awk -F '=' '/^NAME=/ { print tolower($2) }' | \
   sed 's/\"//g')

set distdir "$DIR/distrib.d/$distribution"

if test -z $distribution  -o ! -d $distdir
   echo "distribution '$distribution' not supported"
   exit 1
end


echo "perform '$distribution' installation"
exec fish $distdir/install

