#!/usr/bin/env fish

set device "SYNA3071:00 06CB:82F1 Touchpad"

function configure_touchpad
   xinput set-prop "$device" "Device Enabled" 1
   xinput set-prop "$device" "Coordinate Transformation Matrix" 1.000000 0.000000 0.000000 0.000000 1.000000 0.000000 0.000000 0.000000 1.000000
   xinput set-prop "$device" "Device Accel Profile" 1
   xinput set-prop "$device" "Device Accel Constant Deceleration" 2.500000
   xinput set-prop "$device" "Device Accel Adaptive Deceleration" 1.000000
   xinput set-prop "$device" "Device Accel Velocity Scaling" 12.500000
   xinput set-prop "$device" "Synaptics Edges" 50 1223 36 636
   xinput set-prop "$device" "Synaptics Finger" 25 30 0
   xinput set-prop "$device" "Synaptics Tap Time" 180
   xinput set-prop "$device" "Synaptics Tap Move" 63
   xinput set-prop "$device" "Synaptics Tap Durations" 180 180 100
   xinput set-prop "$device" "Synaptics ClickPad" 1
   xinput set-prop "$device" "Synaptics Middle Button Timeout" 0
   xinput set-prop "$device" "Synaptics Two-Finger Pressure" 282
   xinput set-prop "$device" "Synaptics Two-Finger Width" 7
   xinput set-prop "$device" "Synaptics Scrolling Distance" -28 28
   xinput set-prop "$device" "Synaptics Edge Scrolling" 0 0 0
   xinput set-prop "$device" "Synaptics Two-Finger Scrolling" 1 1
   xinput set-prop "$device" "Synaptics Move Speed" 1.000000 1.750000 0.138985 0.000000
   xinput set-prop "$device" "Synaptics Off" 0
   xinput set-prop "$device" "Synaptics Locked Drags" 0
   xinput set-prop "$device" "Synaptics Locked Drags Timeout" 5000
   xinput set-prop "$device" "Synaptics Tap Action" 0 0 0 0 1 3 2
   xinput set-prop "$device" "Synaptics Click Action" 1 3 2
   xinput set-prop "$device" "Synaptics Circular Scrolling" 0
   xinput set-prop "$device" "Synaptics Circular Scrolling Distance" 0.100000
   xinput set-prop "$device" "Synaptics Circular Scrolling Trigger" 0
   xinput set-prop "$device" "Synaptics Circular Pad" 0
   xinput set-prop "$device" "Synaptics Palm Detection" 1
   xinput set-prop "$device" "Synaptics Palm Dimensions" 3 3
   xinput set-prop "$device" "Synaptics Coasting Speed" 20.000000 50.000000
   xinput set-prop "$device" "Synaptics Pressure Motion" 30 160
   xinput set-prop "$device" "Synaptics Pressure Motion Factor" 1.000000 1.000000
   xinput set-prop "$device" "Synaptics Resolution Detect" 1
   xinput set-prop "$device" "Synaptics Grab Event Device" 0
   xinput set-prop "$device" "Synaptics Gestures" 1
   xinput set-prop "$device" "Synaptics Area" 0 0 0 0
   xinput set-prop "$device" "Synaptics Soft Button Areas" 0 0 0 0 0 0 0 0
   xinput set-prop "$device" "Synaptics Noise Cancellation" 7 7
end

function toggle
   set state (xinput list-props "$device" | \
              grep "Device Enabled" | \
              grep -o '[01]$')

   if test $state -eq 1
      xinput --disable "$device"
   else
      xinput --enable "$device"
   end
end

function parse_args
  argu c configure t toggle -- $argv | while read -l opt value
    switch $opt
      case -c configure
        configure_touchpad
      case -t toggle
        toggle
    end
  end
end

parse_args $argv
