#!/usr/bin/env fish

# Terminate already running bar instances
while killall -q polybar > /dev/null
   sleep 1
end

set primary_display (xrandr --current | \
   rg --only-matching --replace '$name' \
      '^(?P<name>[A-Za-z]+-.+?)\sconnected\sprimary')

env MONITOR=$primary_display nohup polybar bottom -r >/dev/null ^&1 &
env MONITOR=$primary_display nohup polybar top -r > /dev/null ^&1 &
