#!/usr/bin/env fish

# Terminate already running bar instances
while killall -q polybar > /dev/null
   sleep 1
end

set MONITOR (polybar -m | tail -1 | sed -e 's/:.*$//g')

env MONITOR=$MONITOR polybar bottom -r &
env MONITOR=$MONITOR polybar top -r &
