#!/usr/bin/env fish

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u (id -u) -x polybar > /dev/null
   sleep 1
end

polybar mytux -r &
